### ISSUE TITLE
make_project fails

### ISSUE THREAD

**Issue by romw** [BOINC/boinc-ng#445]
**Reported by linuxguru on 26 Nov 37866322 08:26 UTC**
When trying to create a new project on a new server install (svn rev 14140) the programs build, but make_project fails with what looks alike a mysql error.  This is Ubuntu 7.10, but I get the same error on Debian testing.

mysql  Ver 14.12 Distrib 5.0.45, for pc-linux-gnu (i486) using readline 5.2

wxWidgets is version 2.8.4

PHP 5.2.3-1ubuntu6 (cli) (built: Oct  4 2007 23:35:54)

Server version: Apache/2.2.4 (Ubuntu)
Server built:   Oct  4 2007 22:47:20

Python 2.5.1

make_project output:
```
root@jp-laptop:/home/jp/dev/boinc/boinc/tools# ./make_project --test_app test
Creating project 'test' (short name 'test'):
   PROJECT_ROOT = /root/projects/test/
       URL_BASE = http://localhost/
  HTML_USER_URL = http://localhost/test/
   HTML_OPS_URL = http://localhost/test_ops/
        CGI_URL = http://localhost/test_cgi/
        KEY_DIR = /root/projects/test/keys/
        DB_NAME = test
        DB_HOST =

Continue? [ y
Setting up server: creating directories

Keys don't exist in /root/projects/test/keys/; generate them? [Y/n](Y/n])  y
Setting up database/home/jp/dev/boinc/boinc/py/Boinc/database.py:255: Warning: 'TYPE=storage_engine' is deprecated; use 'ENGINE=storage_engine' instead
  cursor.execute(query)

Traceback (most recent call last):
  File "./make_project", line 212, in <module>
    project.install_project()
  File "/home/jp/dev/boinc/boinc/py/Boinc/setup_project.py", line 518, in install_project
    drop_first = options.drop_db_first
  File "/home/jp/dev/boinc/boinc/py/Boinc/database.py", line 269, in create_database
    _execute_sql_script(cursor, os.path.join(schema_path, file))
  File "/home/jp/dev/boinc/boinc/py/Boinc/database.py", line 255, in _execute_sql_script
    cursor.execute(query)
  File "/var/lib/python-support/python2.5/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/var/lib/python-support/python2.5/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '- entity type to which this forum is attached:\n        - 0 == category (public)\n' at line 23")
```

./configure output:

[- too long](removed)

**Comment by romw** [comment]
**Commented by Nicolas on 24 Mar 37866353 17:46 UTC**
Fixed in [14141]. Also, you should be using ```./configure --disable-client```. The 6.1.0 client is nowhere near ready to use.

**Comment by romw** [comment]
**Commented by linuxguru on 22 Mar 37867294 20:53 UTC**
Replying to [Nicolas](comment:1):
> Fixed in [14141]. Also, you should be using ```./configure --disable-client```. The 6.1.0 client is nowhere near ready to use.

I confirm the problem is fixed.

What client should I be using?
