### ISSUE TITLE
Fix error source for a SIGSEGV crash during exit of manager application

### ISSUE THREAD

**Issue by romw** [BOINC/boinc-ng#900]
**Reported by elfring on 4 Apr 39473725 10:40 UTC**
I have dared to build the [current development software](wiki:SourceCode) (release 6.9.0) on my Linux system.

I notice unexpected behaviour after I click on the X (close) button of the application window because a red "Error" was displayed in the GUI.

```
elfring@Sonne:~> gdb boincmgr
GNU gdb (GDB; openSUSE 11.1) 6.8.50.20081120-cvs
[run
Starting program: /usr/local/bin/boincmgr
[Thread debugging using libthread_db enabled](...]
(gdb))
[Thread 0x7fffe4598950 (LWP 2732)](New)
execvp(/home/elfring/boinc, --redirectio, --launched_by_manager) failed with error 2!
execvp(/home/elfring/boinc, --redirectio, --launched_by_manager) failed with error 2!

Program received signal SIGSEGV, Segmentation fault.
[to Thread 0x7fffe4598950 (LWP 2732)](Switching)
0x00007ffff423df6a in freelocale () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff423df6a in freelocale () from /lib64/libc.so.6
#1  0x000000000043e1da in RPCThread::Entry (this=0xd8f810) at AsyncRPC.cpp:380
#2  0x00007ffff5dc9a41 in wxThreadInternal::PthreadStart(wxThread*) ()
   from /usr/local/lib/../lib64/libwx_baseu-2.8.so.0
#3  0x00007ffff49df070 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff42e610d in clone () from /lib64/libc.so.6
#5  0x0000000000000000 in ?? ()
```

**Comment by romw** [comment]
**Commented by romw on 13 Dec 39832679 16:53 UTC**
This appears to be fixed in 6.10 and trunk.
